Repository tazama-lf/frms-coe-lib, pull requests merged in 2024-11, with the labels that each got.

#203 docs: add documentation for encapsulation of environment variables
  README.md
  VARIABLES.md
Labels: documentation

#217 refactor: update arango schema
  __tests__/collections.test.ts
  __tests__/dbManager.test.ts
  package-lock.json
  package.json
  src/builders/transactionBuilder.ts
  src/builders/transactionHistoryBuilder.ts
  src/interfaces/ArangoCollections.ts
  src/interfaces/database/TransactionDB.ts
  src/interfaces/database/TransactionHistoryDB.ts
Labels: refactor

#222 fix: missing fields in message types
  package-lock.json
  package.json
  src/interfaces/Pacs.008.001.10.ts
  src/interfaces/Pain.013.001.09.ts
  src/tests/data/pacs008.ts
  src/tests/data/pain013.ts
Labels: bug
