Repository tazama-lf/frms-coe-lib, pull requests merged in 2024-10, with the labels that each got.

#177 feat: env variable validation
  __tests__/env.test.ts
  src/helpers/env/database.config.ts
  src/helpers/env/index.ts
  src/helpers/env/monitoring.config.ts
  src/helpers/env/processor.config.ts
  src/helpers/env/redis.config.ts
Labels: enhancement

#179 build: 4.2.0-rc.1
  package-lock.json
  package.json
Labels: build

#180 refactor: reuse available redis config
  src/helpers/env/redis.config.ts
Labels: refactor

#181 feat: optional variables
  src/helpers/env/database.config.ts
  src/helpers/env/index.ts
  src/helpers/env/monitoring.config.ts
  src/helpers/env/redis.config.ts
Labels: enhancement

#182 build: prepare 4.2.0-rc.2 release
  package-lock.json
  package.json
Labels: build

#183 fix: optional variables
  src/helpers/env/index.ts
Labels: bug

#184 build: 4.2.0-rc.3
  package-lock.json
  package.json
Labels: build

#192 fix: split cache options
  README.md
  __tests__/dbManager.test.ts
  src/builders/configurationBuilder.ts
  src/helpers/env/database.config.ts
  src/helpers/env/index.ts
  src/helpers/env/localcache.config.ts
  src/helpers/env/redis.config.ts
  src/interfaces/RedisConfig.ts
  src/services/dbManager.ts
Labels: bug

#193 refactor: 5.0.0-rc.0
  package-lock.json
  package.json
Labels: refactor

#187 fix: db user is not required if auth is disabled
  src/helpers/env/database.config.ts
  src/helpers/env/index.ts
Labels: bug

#195 refactor: Add validation on create
  __tests__/env.test.ts
  package-lock.json
  package.json
  src/config.ts
  src/config/database.config.ts
  src/config/index.ts
  src/config/localcache.config.ts
  src/config/monitoring.config.ts
  src/config/processor.config.ts
  src/config/redis.config.ts
  src/helpers/env/redis.config.ts
  src/services/apm.ts
  src/services/dbManager.ts
  src/services/logger.ts
Labels: refactor

#189 fix: Issue 227 Add Tazama into to LICENSE
  LICENSE
Labels: bug

#200 refactor: clean before build
  package-lock.json
  package.json
Labels: refactor

#206 feat: Multi currency cache
  __tests__/dbManager.test.ts
  package-lock.json
  package.json
  src/helpers/proto/Full.proto
  src/interfaces/Pacs.008.001.10.ts
  src/interfaces/Pain.001.001.11.ts
  src/interfaces/rule/DataCache.ts
Labels: enhancement
