Repository tazama-lf/frms-coe-lib, pull requests merged in 2024-08, with the labels that each got.

#153 docs: full rework of readMe
  README.md
Labels: documentation

#155 feat: Event flow entity condition
  __tests__/collections.test.ts
  __tests__/dbManager.test.ts
  package-lock.json
  package.json
  src/builders/pseudonymsBuilder.ts
  src/helpers/proto/Full.proto
  src/interfaces/ArangoCollections.ts
  src/interfaces/database/PseudonymsDB.ts
  src/interfaces/event-flow/AccountCondition.ts
  src/interfaces/event-flow/Condition.ts
  src/interfaces/event-flow/ConditionEdge.ts
  src/interfaces/event-flow/EntityCondition.ts
  src/interfaces/index.ts
  src/interfaces/processor-files/TypologyConfig.ts
  src/interfaces/processor-files/TypologyResult.ts
Labels: enhancement

#161 docs: update readme
  README.md
Labels: documentation

#162 fix: remove key override and edge separation
  __tests__/dbManager.test.ts
  package-lock.json
  package.json
  src/builders/pseudonymsBuilder.ts
  src/interfaces/ArangoCollections.ts
  src/interfaces/database/PseudonymsDB.ts
Labels: bug

#163 feat: proto encode/decode EFRUP conditions
  __tests__/utils.test.ts
  package-lock.json
  package.json
  src/helpers/proto/EFRuP.proto
  src/helpers/protobuf.ts
  src/interfaces/event-flow/ConditionDetails.ts
Labels: enhancement

#165 feat: Cond id auto gen using UUID v4
  package-lock.json
  package.json
  src/builders/pseudonymsBuilder.ts
  src/interfaces/event-flow/Condition.ts
Labels: enhancement
