Repository tazama-lf/frms-coe-lib, pull requests merged in 2024-07, with the labels that each got.

#134 feat: Enhancement to the release workflow
  .github/workflows/release.yml
Labels: enhancement

#137 build: version bump
  package-lock.json
  package.json
Labels: build

#139 fix: remove private modifiers on logger
  package-lock.json
  package.json
  src/services/lumberjackGRPCService.ts
Labels: bug

#140 build: bumped version for release 2.0.0
  package-lock.json
  package.json
Labels: build

#142 build: update lockfile
  package-lock.json
Labels: build

#141 fix: Version bumping
  CHANGELOG.md
  VERSION
  package-lock.json
  package.json
  src/services/lumberjackGRPCService.ts
Labels: bug
